### ISSUE TITLE
[1.8.8] Crash when right-clicking Execution Module with empty Code Bible

### ISSUE THREAD

**Issue by wlhlm** [MightyPirates/TIS-3D#24]
On 1.8.8, right-clicking an Execution Module with an empty Code Bible results in the immediate termination of the game.

[Crashlog](http://paste.ee/p/txXvL)

Stacktrace:
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_66]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_66]
	at li.cil.tis3d.common.item.ItemBookCode$Data.getProgram(ItemBookCode.java:145) ~[ItemBookCode$Data.class:?]
	at li.cil.tis3d.common.module.ModuleExecution$SourceCodeProviderBookCode.codeFor(ModuleExecution.java:458) ~[ModuleExecution$SourceCodeProviderBookCode.class:?]
	at li.cil.tis3d.common.module.ModuleExecution.onActivate(ModuleExecution.java:180) ~[ModuleExecution.class:?]
	at li.cil.tis3d.common.block.BlockCasing.func_180639_a(BlockCasing.java:158) ~[BlockCasing.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_178890_a(PlayerControllerMP.java:377) ~[bda.class:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1491) ~[ave.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2036) ~[ave.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024) ~[ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
```

Forge 1638
TIS-3D 0.2.0.25

**Comment by fnuecke** [comment]
Ah, right. Thanks for reporting! Will fix when I get home.

**Comment by wlhlm** [comment]
Thanks for the fix!
