### ISSUE TITLE
Crash on execution

### ISSUE THREAD

**Issue by PrinzJuliano** [MightyPirates/TIS-3D#38]
ISSUE: When I programmed the blocks and flick the lever for execution the game crashes!
My Stacktrace:
Time: 03.01.16 13:32
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.block.Block.doesSideBlockRendering(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/BlockPos;Lnet/minecraft/util/EnumFacing;)Z
    at li.cil.tis3d.api.prefab.module.AbstractModule.isVisible(AbstractModule.java:162)
    at li.cil.tis3d.common.module.ModuleExecution.sendPartialState(ModuleExecution.java:343)
    at li.cil.tis3d.common.module.ModuleExecution.step(ModuleExecution.java:122)
    at li.cil.tis3d.common.machine.CasingImpl.stepModules(CasingImpl.java:116)
    at li.cil.tis3d.common.tile.TileEntityCasing.stepModules(TileEntityCasing.java:163)
    at li.cil.tis3d.common.tile.TileEntityController$$Lambda$83/205223229.accept(Unknown Source)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at li.cil.tis3d.common.tile.TileEntityController.step(TileEntityController.java:468)
    at li.cil.tis3d.common.tile.TileEntityController.func_73660_a(TileEntityController.java:306)
    at net.minecraft.world.World.func_72939_s(World.java:1716)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at li.cil.tis3d.api.prefab.module.AbstractModule.isVisible(AbstractModule.java:162)
    at li.cil.tis3d.common.module.ModuleExecution.sendPartialState(ModuleExecution.java:343)
    at li.cil.tis3d.common.module.ModuleExecution.step(ModuleExecution.java:122)
    at li.cil.tis3d.common.machine.CasingImpl.stepModules(CasingImpl.java:116)
    at li.cil.tis3d.common.tile.TileEntityCasing.stepModules(TileEntityCasing.java:163)
    at li.cil.tis3d.common.tile.TileEntityController$$Lambda$83/205223229.accept(Unknown Source)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at li.cil.tis3d.common.tile.TileEntityController.step(TileEntityController.java:468)
    at li.cil.tis3d.common.tile.TileEntityController.func_73660_a(TileEntityController.java:306)

-- Block entity being ticked --
Details:
    Name: controller // li.cil.tis3d.common.tile.TileEntityController
    Block type: ID #236 (tile.tis3d.controller // li.cil.tis3d.common.block.BlockController)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (243,65,273), Chunk: (at 3,4,1 in 15,17; contains blocks 240,0,272 to 255,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #236 (tile.tis3d.controller // li.cil.tis3d.common.block.BlockController)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1716)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)

-- Affected level --
Details:
    Level name: TIS
    All players: 1 total; [EntityPlayerMP['PrinzJuliano'/174, l='TIS', x=240,13, y=65,00, z=273,70]]
    Chunk stats: ServerChunkCache: 1167 Drop: 0
    Level seed: 2995479536448582658
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: 228,00,64,00,252,00 - World: (228,64,252), Chunk: (at 4,4,12 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 3556 game time, 3556 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 19285 (now: false), thunder time: 64095 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.8.8
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 253841512 bytes (242 MB) / 686305280 bytes (654 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.18 Powered by Forge 11.15.0.1591 5 mods loaded, 5 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.18} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.8-11.15.0.1591-1.8.8.jar) 
    UCHIJAAAA   Forge{11.15.0.1591} [Minecraft Forge](forge-1.8.8-11.15.0.1591-1.8.8.jar) 
    UCHIJAAAA   JEI{2.12.0.49} [Just Enough Items](jei_1.8.8-2.12.0.49.jar) 
    UCHIJAAAA   tis3d{0.8.1.76} [TIS-3D](TIS-3D-MC1.8.8-0.8.1.76.jar) 
    Loaded coremods (and transformers): 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['PrinzJuliano'/174, l='TIS', x=240,13, y=65,00, z=273,70]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by fnuecke** [comment]
Could you please try updating your Forge version? If that fixes it, I'll look into when that method was added and add an appropriate version requirement.

**Comment by Vexatos** [comment]
[The commit](https://github.com/MinecraftForge/MinecraftForge/commit/ea75a3be69bd0892a0e4b5b1b437b3d1094ad32e)
Added in [Build 1.8.8-11.15.0.1655](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.8.8-11.15.0.1655/forge-1.8.8-11.15.0.1655-changelog.txt).

**Comment by fnuecke** [comment]
Thanks!

**Comment by fnuecke** [comment]
4c6e8af06f035c88a2d865f8e9887ede8410ac2b
