### ISSUE TITLE
{Rift - 0.0.4] Crash on World Load

### ISSUE THREAD

**Issue by Knito58** [MightyPirates/TIS-3D#84]
https://pastebin.com/iEXBBauY

Description: Initializing game
 
java.lang.NoSuchMethodError: ddb.a(Lve;Lpc;)V
    at li.cil.tis3d.client.renderer.TextureLoader.loadTextureLocations(TextureLoader.java:45)
    at ddb.lambda$func_195426_a$0(TextureMap.java:1145)
    at ddb$$Lambda$927/2013921819.accept(Unknown Source)
    bla....

**Comment by fnuecke** [comment]
Hmm, @asiekierka any idea what could've caused this?

**Comment by asiekierka** [comment]
Yes, this is a known issue with OptiFine.

**Comment by Knito58** [comment]
Ok I uninstall Optifine and check this.

**Comment by Knito58** [comment]
Yep. It was Optifine. Thank you.
